# Generated by Django 2.2.1 on 2019-05-12 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Project',
        ),
    ]
