# Generated by Django 2.2.1 on 2019-05-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects')),
                ('create', models.TimeField(auto_now_add=True, verbose_name='date create')),
                ('update', models.TimeField(auto_now=True, verbose_name='date update')),
            ],
        ),
    ]
