# Generated by Django 2.2.1 on 2019-05-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portada', '0002_auto_20190512_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date create'),
        ),
        migrations.AlterField(
            model_name='project',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='date update'),
        ),
    ]
